
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Ivan\Ivan\Ivan\Deg CS\ALL Project\Car2U\Car2U codes\Testing\build\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    946.0,
    403.0,
    1238.0,
    596.0,
    fill="#D6F0FF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    45.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    47.0,
    136.0,
    image=image_image_2
)

canvas.create_text(
    94.0,
    116.0,
    anchor="nw",
    text="Booking Details",
    fill="#000000",
    font=("Sintony Bold", 30 * -1)
)

canvas.create_text(
    1050.0,
    540.0,
    anchor="nw",
    text="MYR 800.00",
    fill="#000000",
    font=("Sintony Bold", 30 * -1)
)

canvas.create_text(
    1009.0,
    183.0,
    anchor="nw",
    text="Checkout Details",
    fill="#000000",
    font=("Sintony Bold", 20 * -1)
)

canvas.create_text(
    681.0,
    183.0,
    anchor="nw",
    text="Pickup / \nDrop-off Details",
    fill="#000000",
    font=("Sintony Bold", 20 * -1)
)

canvas.create_rectangle(
    36.0,
    171.0,
    583.0,
    620.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    610.0,
    171.0,
    903.0,
    620.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    930.0,
    171.0,
    1254.0,
    620.0,
    fill="#FFFFFF",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    309.0,
    289.0,
    image=image_image_3
)

canvas.create_text(
    184.0,
    426.0,
    anchor="nw",
    text="Mazda-CX5 | Red",
    fill="#000000",
    font=("Sintony Bold", 30 * -1)
)

canvas.create_text(
    955.0,
    238.0,
    anchor="nw",
    text="J & C Rental Agency",
    fill="#000000",
    font=("Sintony", 18 * -1)
)

canvas.create_text(
    955.0,
    425.0,
    anchor="nw",
    text="Payment Summary",
    fill="#000000",
    font=("Sintony", 18 * -1)
)

canvas.create_text(
    955.0,
    459.0,
    anchor="nw",
    text="Rental per Day",
    fill="#000000",
    font=("Sintony", 13 * -1)
)

canvas.create_text(
    1138.0,
    459.0,
    anchor="nw",
    text="MYR 160.00",
    fill="#000000",
    font=("Sintony", 13 * -1)
)

canvas.create_text(
    955.0,
    489.0,
    anchor="nw",
    text="Subtotal",
    fill="#000000",
    font=("Sintony", 13 * -1)
)

canvas.create_text(
    1138.0,
    489.0,
    anchor="nw",
    text="MYR 800.00",
    fill="#000000",
    font=("Sintony", 13 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    408.0,
    501.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    408.0,
    570.0,
    image=image_image_5
)

canvas.create_text(
    451.0,
    493.0,
    anchor="nw",
    text="4-seater",
    fill="#000000",
    font=("Sintony", 18 * -1)
)

canvas.create_text(
    451.0,
    561.0,
    anchor="nw",
    text="Automatic",
    fill="#000000",
    font=("Sintony", 18 * -1)
)

canvas.create_text(
    155.0,
    495.0,
    anchor="nw",
    text="MAZDA",
    fill="#000000",
    font=("Sintony", 18 * -1)
)

canvas.create_text(
    155.0,
    559.0,
    anchor="nw",
    text="Petrol",
    fill="#000000",
    font=("Sintony", 18 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    114.0,
    504.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    114.0,
    570.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    753.0,
    413.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    975.0,
    285.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    975.0,
    340.0,
    image=image_image_10
)

canvas.create_text(
    1014.0,
    272.0,
    anchor="nw",
    text="13, Jalan Cempaka, \n51300 Selangor, Malaysia.",
    fill="#000000",
    font=("Sintony", 13 * -1)
)

canvas.create_text(
    1014.0,
    335.0,
    anchor="nw",
    text="04-3928750",
    fill="#000000",
    font=("Sintony", 13 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=535.0,
    y=643.0,
    width=210.0,
    height=55.0
)
window.resizable(False, False)
window.mainloop()
